# fly.toml app configuration file generated for designx on 2023-06-23T18:59:12+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "designx"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
